---
# This playbook deploys the whole application stack in this site.

- name: apply common configuration to all nodes
  hosts: all
  remote_user: root
  #become: True
  #become_method: sudo

  roles:
    - role: roles/chia-miner-install
